project_id = "ryhwcwnlcuqzbnnfhskq"

[functions.generate-pdf]
verify_jwt = true

[functions.process-coop-cart]
verify_jwt = false

[functions.notify-coop-deadline]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = true

[functions.export-analytics]
verify_jwt = true

[functions.notify-referral]
verify_jwt = false
